// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class AboutTextId : uint16_t {
  AboutQrTooBig,
  AboutSupportDevelopment,
  Count
};

inline const char* generatedAboutLocaleString(uint8_t localeIndex, AboutTextId id) {
  static const char* const STRINGS_0[] = {
    "QR too big",
    "Support development",
  };
  static const char* const STRINGS_1[] = {
    "QR-koden är för stor",
    "Stöd utvecklingen",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)AboutTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
