// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class AirtimeTextId : uint16_t {
  AirtimeTabBudget,
  AirtimeTabHistory,
  AirtimeNoData,
  AirtimeTxFree,
  AirtimeNoHistory,
  Count
};

inline const char* generatedAirtimeLocaleString(uint8_t localeIndex, AirtimeTextId id) {
  static const char* const STRINGS_0[] = {
    "Budget",
    "History",
    "No airtime data",
    "TX free",
    "No history",
  };
  static const char* const STRINGS_1[] = {
    "Budget",
    "Historik",
    "Ingen sändtidsdata",
    "TX ledig",
    "Ingen historik",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)AirtimeTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
