// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ChannelShareTextId : uint16_t {
  ChannelShareNoKey,
  ChannelShareQrTooBig,
  ChannelShareShowQr,
  ChannelShareShowKey,
  Count
};

inline const char* generatedChannelShareLocaleString(uint8_t localeIndex, ChannelShareTextId id) {
  static const char* const STRINGS_0[] = {
    "No key",
    "QR too big",
    "Center to show QR",
    "Center to show key",
  };
  static const char* const STRINGS_1[] = {
    "Ingen nyckel",
    "QR-koden är för stor",
    "Select för att visa QR",
    "Select för att visa nyckel",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ChannelShareTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
