// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ChatNotifyTextId : uint16_t {
  ChatNotifySound,
  ChatNotifyAll,
  ChatNotifyMentionsOnly,
  ChatNotifyMute,
  Count
};

inline const char* generatedChatNotifyLocaleString(uint8_t localeIndex, ChatNotifyTextId id) {
  static const char* const STRINGS_0[] = {
    "Sound",
    "All",
    "Mentions only",
    "Mute",
  };
  static const char* const STRINGS_1[] = {
    "Ljud",
    "Alla",
    "Endast omnämnanden",
    "Tysta",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ChatNotifyTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
