// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ChatMenuTextId : uint16_t {
  ChatMenuRegion,
  ChatMenuNotifications,
  ChatMenuShare,
  ChatMenuClearChat,
  ChatMenuMarkUnread,
  ChatMenuDeleteChat,
  ChatMenuNone,
  ChatMenuAll,
  ChatMenuMentions,
  ChatMenuMute,
  ChatMenuMarkedUnread,
  ChatMenuConfirmClear,
  ChatMenuConfirmDelete,
  ChatMenuCleared,
  ChatMenuDeleted,
  Count
};

inline const char* generatedChatMenuLocaleString(uint8_t localeIndex, ChatMenuTextId id) {
  static const char* const STRINGS_0[] = {
    "Region",
    "Notifications",
    "Share",
    "Clear chat",
    "Mark unread",
    "Delete chat",
    "None",
    "All",
    "Mentions",
    "Mute",
    "Marked unread",
    "Clear this chat?",
    "Delete this chat?",
    "Chat cleared",
    "Chat deleted",
  };
  static const char* const STRINGS_1[] = {
    "Region",
    "Aviseringar",
    "Dela",
    "Rensa chatt",
    "Markera oläst",
    "Ta bort chatt",
    "Ingen",
    "Alla",
    "Omnämnanden",
    "Tyst",
    "Markerad som oläst",
    "Rensa den här chatten?",
    "Ta bort den här chatten?",
    "Chatten rensad",
    "Chatten borttagen",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ChatMenuTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
