// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once
#include <stddef.h>
#include <stdint.h>
namespace mishmesh {
enum class ClockAlertTextId : uint16_t {
  ClockAlertAlarm,
  ClockAlertTimerDone,
  ClockAlertPressAnyKey,
  Count
};
inline const char* generatedClockAlertLocaleString(uint8_t localeIndex, ClockAlertTextId id) {
  static const char* const STRINGS_0[] = {"Alarm", "Timer done", "Press any key to dismiss"};
  static const char* const STRINGS_1[] = {"Alarm", "Timern är klar", "Tryck på valfri knapp för att stänga"};
  static const char* const* const TABLES[] = {STRINGS_0, STRINGS_1};
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ClockAlertTextId::Count) return nullptr;
  return TABLES[localeIndex][textIndex];
}
}  // namespace mishmesh
