// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ClockTextId : uint16_t {
  ClockTabStopwatch,
  ClockTabTimer,
  ClockTabAlarm,
  ClockTabWorld,
  ClockTabSettings,
  ClockWorldAddCity,
  ClockStopwatchRunningHint,
  ClockStopwatchResumeHint,
  ClockStopwatchStartHint,
  ClockTimerPaused,
  ClockTimerRunningHint,
  ClockTimerResumeHint,
  ClockTimerSetHint,
  ClockAlarmClockNotSet,
  ClockAlarmRingsNow,
  ClockAlarmRingsInHours,
  ClockAlarmRingsInMinutes,
  ClockAlarmTimeTitle,
  ClockAlarmTimeLabel,
  ClockAlarmEnabledLabel,
  ClockAlarmSet,
  ClockWorldAlreadyAdded,
  ClockWorldCityRemoved,
  Count
};

inline const char* generatedClockLocaleString(uint8_t localeIndex, ClockTextId id) {
  static const char* const STRINGS_0[] = {
    "Stopwatch",
    "Timer",
    "Alarm",
    "World",
    "Settings",
    "Add city",
    "Sel stop / up lap / hold reset",
    "Sel resume / hold reset",
    "Select to start",
    "Paused",
    "Sel pause / hold reset",
    "Sel resume / hold reset",
    "Up/down set / sel start",
    "Clock not set",
    "Rings now",
    "Rings in %ldh %02ldm",
    "Rings in %ldm",
    "Alarm time",
    "Time",
    "Enabled",
    "Alarm set",
    "Already added",
    "City removed",
  };
  static const char* const STRINGS_1[] = {
    "Stoppur",
    "Timer",
    "Alarm",
    "Värld",
    "Inställningar",
    "Lägg till stad",
    "Sel stopp / upp varv / håll reset",
    "Sel fortsätt / håll reset",
    "Select för start",
    "Pausad",
    "Sel paus / håll reset",
    "Sel fortsätt / håll reset",
    "Upp/ned ställ / Sel start",
    "Klockan ej ställd",
    "Ringer nu",
    "Ringer om %ldh %02ldm",
    "Ringer om %ldm",
    "Alarmtid",
    "Tid",
    "Aktiverat",
    "Alarm inställt",
    "Redan tillagd",
    "Stad borttagen",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ClockTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
