// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once
#include <stddef.h>
#include <stdint.h>
namespace mishmesh {
enum class CommandLineTextId : uint16_t {
  CommandLineSendFailed,
  CommandLineNoResponse,
  CommandLineWaitingReply,
  CommandLineSelectCommand,
  CommandLineCommand,
  Count
};
inline const char* generatedCommandLineLocaleString(uint8_t localeIndex, CommandLineTextId id) {
  static const char* const STRINGS_0[] = {
    "[send failed]", "[no response]", "Waiting reply...", "Select: command", "Command",
  };
  static const char* const STRINGS_1[] = {
    "[kunde inte skicka]", "[inget svar]", "Väntar på svar...", "Select: kommando", "Kommando",
  };
  static const char* const* const TABLES[] = {STRINGS_0, STRINGS_1};
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)CommandLineTextId::Count) return nullptr;
  return TABLES[localeIndex][textIndex];
}
}  // namespace mishmesh
