// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ContactDetailTextId : uint16_t {
  ContactDetailViewDetails,
  ContactDetailTelemetry,
  ContactDetailPingZeroHop,
  ContactDetailResetPath,
  ContactDetailClearConversation,
  ContactDetailDeleteContact,
  ContactDetailSendMessage,
  ContactDetailRename,
  ContactDetailPermissions,
  ContactDetailSetPath,
  ContactDetailManage,
  ContactDetailRemoveFavorite,
  ContactDetailAddFavorite,
  ContactDetailHashSize,
  ContactDetailFlood,
  ContactDetailOneHop,
  ContactDetailHops,
  ContactDetailInvalidPath,
  ContactDetailPathSaved,
  ContactDetailPathCleared,
  ContactDetailFailed,
  ContactDetailType,
  ContactDetailPathDirect,
  ContactDetailPathFlood,
  ContactDetailDistance,
  ContactDetailLastHeard,
  ContactDetailGps,
  ContactDetailPublicKey,
  ContactDetailCleared,
  ContactDetailDeleted,
  ContactDetailAddedFavorite,
  ContactDetailRemovedFavorite,
  ContactDetailPathReset,
  ContactDetailConfirmClear,
  ContactDetailConfirmDelete,
  Count
};

inline const char* generatedContactDetailLocaleString(uint8_t localeIndex, ContactDetailTextId id) {
  static const char* const STRINGS_0[] = {
    "View details",
    "Telemetry",
    "Ping (0 hop)",
    "Reset path",
    "Clear conversation",
    "Delete contact",
    "Send message",
    "Rename",
    "Permissions",
    "Set path",
    "Manage",
    "Remove from favorites",
    "Add to favorites",
    "%d-byte (%d hops)",
    "flood",
    "1 hop",
    "%d hops",
    "Invalid path",
    "Path saved",
    "Path cleared",
    "Failed",
    "Type: %s",
    "Path: Direct (%u hop)",
    "Path: Flood",
    "Distance: %.2f km",
    "Last heard: %s ago",
    "GPS: %.5f, %.5f",
    "Public key:",
    "Cleared",
    "Contact deleted",
    "Added to favorites",
    "Removed from favorites",
    "Path reset",
    "Clear conversation?",
    "Delete this contact?",
  };
  static const char* const STRINGS_1[] = {
    "Visa detaljer",
    "Telemetri",
    "Ping (0 hopp)",
    "Återställ rutt",
    "Rensa konversation",
    "Ta bort kontakt",
    "Skicka meddelande",
    "Byt namn",
    "Behörigheter",
    "Ange rutt",
    "Hantera",
    "Ta bort från favoriter",
    "Lägg till i favoriter",
    "%d byte (%d hopp)",
    "flood",
    "1 hopp",
    "%d hopp",
    "Ogiltig rutt",
    "Rutten sparad",
    "Rutten rensad",
    "Misslyckades",
    "Typ: %s",
    "Rutt: Direkt (%u hopp)",
    "Rutt: Flood",
    "Avstånd: %.2f km",
    "Senast hörd: %s sedan",
    "GPS: %.5f, %.5f",
    "Publik nyckel:",
    "Rensad",
    "Kontakten borttagen",
    "Tillagd i favoriter",
    "Borttagen från favoriter",
    "Rutten återställd",
    "Rensa konversationen?",
    "Ta bort den här kontakten?",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ContactDetailTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
