// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class DiscoverDetailTextId : uint16_t {
  DiscoverDetailAddToContacts,
  DiscoverDetailViewDetails,
  DiscoverDetailType,
  DiscoverDetailDistance,
  DiscoverDetailLastHeard,
  DiscoverDetailGps,
  DiscoverDetailPublicKey,
  DiscoverDetailAdded,
  DiscoverDetailAddFailed,
  Count
};

inline const char* generatedDiscoverDetailLocaleString(uint8_t localeIndex, DiscoverDetailTextId id) {
  static const char* const STRINGS_0[] = {
    "Add to contacts",
    "View details",
    "Type: %s",
    "Distance: %.2f km",
    "Last heard: %s ago",
    "GPS: %.5f, %.5f",
    "Public key:",
    "Added to contacts",
    "Couldn't add contact",
  };
  static const char* const STRINGS_1[] = {
    "Lägg till i kontakter",
    "Visa detaljer",
    "Typ: %s",
    "Avstånd: %.2f km",
    "Senast hörd: %s sedan",
    "GPS: %.5f, %.5f",
    "Publik nyckel:",
    "Tillagd i kontakter",
    "Kunde inte lägga till kontakt",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)DiscoverDetailTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
