// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once
#include <stddef.h>
#include <stdint.h>
namespace mishmesh {
enum class JoinPrivateTextId : uint16_t {
  JoinPrivateName,
  JoinPrivateKey,
  JoinPrivateJoin,
  JoinPrivateNone,
  JoinPrivateTitle,
  JoinPrivateKey32Hex,
  JoinPrivateNameRequired,
  JoinPrivateKey32HexChars,
  Count
};
inline const char* generatedJoinPrivateLocaleString(uint8_t localeIndex, JoinPrivateTextId id) {
  static const char* const STRINGS_0[] = {
    "Name", "Key", "Join", "(none)", "Join private", "Key (32 hex)",
    "Name required", "Key: 32 hex chars",
  };
  static const char* const STRINGS_1[] = {
    "Namn", "Nyckel", "Gå med", "(ingen)", "Gå med i privat kanal", "Nyckel (32 hex)",
    "Namn krävs", "Nyckel: 32 hextecken",
  };
  static const char* const* const TABLES[] = {STRINGS_0, STRINGS_1};
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)JoinPrivateTextId::Count) return nullptr;
  return TABLES[localeIndex][textIndex];
}
}  // namespace mishmesh
