// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class TextId : uint16_t {
  AppSettings,
  SettingsHome,
  SettingsContacts,
  SettingsMessages,
  SettingsAdvert,
  SettingsRadio,
  SettingsTimeDate,
  SettingsLanguage,
  SettingsSystemInfo,
  SettingsResetOnboarding,
  HomeBatteryPercent,
  HomeScreenSleep,
  HomeLeftShortcut,
  HomeRightShortcut,
  AppMessages,
  AppContacts,
  AppAdvert,
  AppClock,
  AppAirtime,
  AppAbout,
  Count
};

struct LocaleDescriptor {
  const char* tag;
  const char* name;
};

inline uint8_t generatedLocaleCount() {
  return 2;
}

inline const LocaleDescriptor& generatedLocaleDescriptor(uint8_t index) {
  static const LocaleDescriptor DESCRIPTORS[] = {
    {"en_US", "English"},
    {"sv_SE", "Svenska"},
  };
  if (index >= generatedLocaleCount()) index = 0;
  return DESCRIPTORS[index];
}

inline const char* generatedLocaleString(uint8_t localeIndex, TextId id) {
  static const char* const STRINGS_0[] = {
    "Settings",
    "Home",
    "Contacts",
    "Messages",
    "Advert",
    "Radio",
    "Time & date",
    "Language",
    "System Info",
    "Reset onboarding",
    "Battery percent",
    "Screen sleep",
    "Left shortcut",
    "Right shortcut",
    "Messages",
    "Contacts",
    "Advert",
    "Clock",
    "Airtime",
    "About",
  };
  static const char* const STRINGS_1[] = {
    "Inställningar",
    "Hem",
    "Kontakter",
    "Meddelanden",
    "Annonsering",
    "Radio",
    "Tid och datum",
    "Språk",
    "Systeminfo",
    "Återställ introduktion",
    "Batteriprocent",
    "Skärmsläckning",
    "Vänster genväg",
    "Höger genväg",
    "Meddelanden",
    "Kontakter",
    "Annonsera",
    "Klocka",
    "Sändtid",
    "Om",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= generatedLocaleCount() || textIndex >= (uint16_t)TextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
