// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class LockTextId : uint16_t {
  LockUnlocked,
  LockLocked,
  LockBackThree,
  Count
};

inline const char* generatedLockLocaleString(uint8_t localeIndex, LockTextId id) {
  static const char* const STRINGS_0[] = {
    "Unlocked",
    "Locked",
    "Back x3 to unlock",
  };
  static const char* const STRINGS_1[] = {
    "Upplåst",
    "Låst",
    "Bakåt x3 för att låsa upp",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)LockTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
