// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class MessagePathTextId : uint16_t {
  MessagePathHeardRepeats,
  MessagePathHeardOnce,
  MessagePathHeardTimes,
  MessagePathDetailsUnavailable,
  MessagePathNotHeardYet,
  MessagePathDirectParenthesized,
  MessagePathDirect,
  MessagePathOneHop,
  MessagePathHops,
  MessagePathNoPath,
  Count
};

inline const char* generatedMessagePathLocaleString(uint8_t localeIndex, MessagePathTextId id) {
  static const char* const STRINGS_0[] = {
    "Heard repeats",
    "Heard 1 time",
    "Heard %u times",
    "Details not available",
    "Not heard yet",
    "  (direct)",
    "Direct",
    "Path: 1 hop",
    "Path: %u hops",
    "Direct (no path)",
  };
  static const char* const STRINGS_1[] = {
    "Hörda repetitioner",
    "Hörd 1 gång",
    "Hörd %u gånger",
    "Detaljer saknas",
    "Inte hörd än",
    "  (direkt)",
    "Direkt",
    "Rutt: 1 hopp",
    "Rutt: %u hopp",
    "Direkt (ingen rutt)",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)MessagePathTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
