// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class MessageThreadTextId : uint16_t {
  MessageThreadReply,
  MessageThreadResend,
  MessageThreadDelete,
  MessageThreadHeardRepeats,
  MessageThreadViewPath,
  MessageThreadHeard,
  MessageThreadSent,
  MessageThreadDelivered,
  MessageThreadFailed,
  MessageThreadRetrying,
  MessageThreadSettings,
  MessageThreadWriteAMessage,
  MessageThreadQuickReplies,
  MessageThreadNoMessages,
  MessageThreadResending,
  MessageThreadResendFailed,
  MessageThreadNoQuickReplies,
  MessageThreadMessage,
  MessageThreadSendFailed,
  MessageThreadRegion,
  Count
};

inline const char* generatedMessageThreadLocaleString(uint8_t localeIndex,
                                                       MessageThreadTextId id) {
  static const char* const STRINGS_0[] = {
    "Reply",
    "Resend",
    "Delete",
    "Heard Repeats",
    "View Path",
    "Heard %u",
    "Sent",
    "Delivered %.1fs",
    "Failed",
    "Retrying %u/%u",
    "Settings",
    "Write a message",
    "Quick replies",
    "No messages",
    "Resending",
    "Resend failed",
    "No quick replies\nAdd in Settings",
    "Message",
    "Send failed",
    "Region",
  };
  static const char* const STRINGS_1[] = {
    "Svara",
    "Skicka igen",
    "Ta bort",
    "Hörda upprepningar",
    "Visa rutt",
    "Hörd %u",
    "Skickat",
    "Levererat %.1fs",
    "Misslyckades",
    "Försöker igen %u/%u",
    "Inställningar",
    "Skriv ett meddelande",
    "Snabbsvar",
    "Inga meddelanden",
    "Skickar igen",
    "Kunde inte skicka igen",
    "Inga snabbsvar\nLägg till i Inställningar",
    "Meddelande",
    "Kunde inte skicka",
    "Region",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)MessageThreadTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
