// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class NotificationTextId : uint16_t {
  NotificationNewMessage,
  NotificationSomeone,
  NotificationUnknown,
  NotificationMoreUnread,
  NotificationBackToDismiss,
  Count
};

inline const char* generatedNotificationLocaleString(uint8_t localeIndex,
                                                       NotificationTextId id) {
  static const char* const STRINGS_0[] = {
    "New message",
    "Someone",
    "Unknown",
    "%u more unread",
    "Back to dismiss",
  };
  static const char* const STRINGS_1[] = {
    "Nytt meddelande",
    "Någon",
    "Okänd",
    "%u fler olästa",
    "Bakåt för att stänga",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)NotificationTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
