// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class OnboardingTextId : uint16_t {
  OnboardingTitleWelcome,
  OnboardingTitleDeviceName,
  OnboardingTitleRadioRegion,
  OnboardingTitleGps,
  OnboardingTitleTime,
  OnboardingTitleAllSet,
  OnboardingTitleSetup,
  OnboardingName,
  OnboardingNext,
  OnboardingEnableGps,
  OnboardingTimeZone,
  OnboardingAutoSync,
  OnboardingSetClock,
  OnboardingUnset,
  OnboardingSet,
  OnboardingGetStarted,
  OnboardingYouAreAllSet,
  OnboardingFinish,
  Count
};

inline const char* generatedOnboardingLocaleString(uint8_t localeIndex, OnboardingTextId id) {
  static const char* const STRINGS_0[] = {
    "Welcome",
    "Device name",
    "Radio region",
    "GPS",
    "Time",
    "All set",
    "Setup",
    "Name",
    "Next",
    "Enable GPS",
    "Time zone",
    "Auto-sync",
    "Set clock...",
    "(unset)",
    "(set)",
    "Get started",
    "You're all set",
    "Finish",
  };
  static const char* const STRINGS_1[] = {
    "Välkommen",
    "Enhetsnamn",
    "Radioregion",
    "GPS",
    "Tid",
    "Klart",
    "Konfiguration",
    "Namn",
    "Nästa",
    "Aktivera GPS",
    "Tidszon",
    "Autosynk",
    "Ställ klockan...",
    "(ej angivet)",
    "(inställd)",
    "Kom igång",
    "Allt är klart",
    "Slutför",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)OnboardingTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
