// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class PingDialogTextId : uint16_t {
  PingDialogPinging,
  PingDialogNoResponse,
  PingDialogRoundTrip,
  PingDialogSnrUs,
  PingDialogSnrThem,
  Count
};

inline const char* generatedPingDialogLocaleString(uint8_t localeIndex, PingDialogTextId id) {
  static const char* const STRINGS_0[] = {
    "Pinging...",
    "No response",
    "Round trip: %u ms",
    "SNR us: %.1f dB",
    "SNR them: %.1f dB",
  };
  static const char* const STRINGS_1[] = {
    "Pingar...",
    "Inget svar",
    "Tur och retur: %u ms",
    "SNR hos oss: %.1f dB",
    "SNR hos dem: %.1f dB",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)PingDialogTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
