// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterSettingsTextId : uint16_t {
  RepeaterSettingsName,
  RepeaterSettingsPublicKey,
  RepeaterSettingsRole,
  RepeaterSettingsOwnerInfo,
  RepeaterSettingsLatitude,
  RepeaterSettingsLongitude,
  RepeaterSettingsZeroHopMin,
  RepeaterSettingsFloodHr,
  RepeaterSettingsRepeatMode,
  RepeaterSettingsAdminPassword,
  RepeaterSettingsGuestPassword,
  RepeaterSettingsVersion,
  RepeaterSettingsPublicInfo,
  RepeaterSettingsRadio,
  RepeaterSettingsOwner,
  RepeaterSettingsPosition,
  RepeaterSettingsAdvert,
  RepeaterSettingsRepeat,
  RepeaterSettingsPasswords,
  RepeaterSettingsAccessControl,
  RepeaterSettingsChangeIdentity,
  RepeaterSettingsRegions,
  RepeaterSettingsTelemetry,
  RepeaterSettingsNeighbors,
  RepeaterSettingsActions,
  RepeaterSettingsComingSoon,
  Count
};

inline const char* generatedRepeaterSettingsLocaleString(uint8_t localeIndex,
                                                          RepeaterSettingsTextId id) {
  static const char* const STRINGS_0[] = {
    "Name", "Public key", "Role", "Owner info", "Latitude", "Longitude",
    "Zero-hop min", "Flood hr", "Repeat mode", "Admin pass", "Guest pass",
    "Version", "Public info", "Radio", "Owner", "Position", "Advert",
    "Repeat", "Passwords", "Access control", "Change identity", "Regions",
    "Telemetry", "Neighbors", "Actions", "Coming soon",
  };
  static const char* const STRINGS_1[] = {
    "Namn", "Publik nyckel", "Roll", "Ägarinfo", "Latitud", "Longitud",
    "Nollhopp min", "Flood tim", "Repetitionsläge", "Adminlösenord",
    "Gästlösenord", "Version", "Offentlig info", "Radio", "Ägare",
    "Position", "Annonsering", "Repetition", "Lösenord", "Åtkomstkontroll",
    "Byt identitet", "Regioner", "Telemetri", "Grannar", "Åtgärder",
    "Kommer snart",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterSettingsTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
