// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterAclTextId : uint16_t {
  RepeaterAclAddUser,
  RepeaterAclReadOnly,
  RepeaterAclReadWrite,
  RepeaterAclAdmin,
  RepeaterAclRemove,
  RepeaterAclError,
  RepeaterAclNoResponse,
  RepeaterAclAccess,
  RepeaterAclLoading,
  RepeaterAclWorking,
  RepeaterAclNoUsers,
  Count
};

inline const char* generatedRepeaterAclLocaleString(uint8_t localeIndex, RepeaterAclTextId id) {
  static const char* const STRINGS_0[] = {
    "Add user",
    "Read-only",
    "Read-write",
    "Admin",
    "Remove",
    "Error",
    "[no response]",
    "Access",
    "Loading...",
    "Working...",
    "No users",
  };
  static const char* const STRINGS_1[] = {
    "Lägg till användare",
    "Skrivskyddad",
    "Läs/skriv",
    "Admin",
    "Ta bort",
    "Fel",
    "[inget svar]",
    "Åtkomst",
    "Laddar...",
    "Arbetar...",
    "Inga användare",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterAclTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
