// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterIdentityTextId : uint16_t {
  RepeaterIdentityGenerateRandom,
  RepeaterIdentityEnterSeed,
  RepeaterIdentityBadSeed,
  RepeaterIdentitySelectToApply,
  RepeaterIdentityKeygenFailed,
  RepeaterIdentityApplyFailed,
  RepeaterIdentityIdentity,
  RepeaterIdentityWorking,
  RepeaterIdentityRebooting,
  RepeaterIdentityConfirmReplace,
  RepeaterIdentitySeedTitle,
  Count
};

inline const char* generatedRepeaterIdentityLocaleString(uint8_t localeIndex, RepeaterIdentityTextId id) {
  static const char* const STRINGS_0[] = {
    "Generate random",
    "Enter seed",
    "Bad seed (need 64 hex)",
    "Select to apply",
    "Keygen failed",
    "Apply failed",
    "Identity",
    "Working...",
    "Rebooting...",
    "Replace repeater key + reboot? You must re-add it.",
    "Seed (64 hex)",
  };
  static const char* const STRINGS_1[] = {
    "Generera slumpmässigt",
    "Ange seed",
    "Ogiltig seed (kräver 64 hex)",
    "Select för att tillämpa",
    "Nyckelgenerering misslyckades",
    "Tillämpningen misslyckades",
    "Identitet",
    "Arbetar...",
    "Startar om...",
    "Ersätt repeaternyckeln och starta om? Du måste lägga till den igen.",
    "Seed (64 hex)",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterIdentityTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
