// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterSettingsPanelTextId : uint16_t {
  RepeaterSettingsPanelSave,
  RepeaterSettingsPanelSettings,
  RepeaterSettingsPanelOn,
  RepeaterSettingsPanelOff,
  RepeaterSettingsPanelLoading,
  RepeaterSettingsPanelSaving,
  RepeaterSettingsPanelSaveFailed,
  RepeaterSettingsPanelSelectSave,
  RepeaterSettingsPanelDiscardChanges,
  Count
};

inline const char* generatedRepeaterSettingsPanelLocaleString(uint8_t localeIndex,
                                                               RepeaterSettingsPanelTextId id) {
  static const char* const STRINGS_0[] = {
    "Save",
    "Settings",
    "On",
    "Off",
    "Loading...",
    "Saving %d/%d...",
    "Save failed: %s",
    "Select Save to apply",
    "Discard changes?",
  };
  static const char* const STRINGS_1[] = {
    "Spara",
    "Inställningar",
    "På",
    "Av",
    "Laddar...",
    "Sparar %d/%d...",
    "Kunde inte spara: %s",
    "Välj Spara för att tillämpa",
    "Kassera ändringar?",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterSettingsPanelTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
