// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterManageTextId : uint16_t {
  RepeaterManageStatus,
  RepeaterManageCommand,
  RepeaterManageSettings,
  Count
};

inline const char* generatedRepeaterManageLocaleString(uint8_t localeIndex, RepeaterManageTextId id) {
  static const char* const STRINGS_0[] = {
    "Status",
    "Cmd",
    "Settings",
  };
  static const char* const STRINGS_1[] = {
    "Status",
    "Kommando",
    "Inställningar",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterManageTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
