// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterRegionsTextId : uint16_t {
  RepeaterRegionsAddRegion,
  RepeaterRegionsDeleteRegion,
  RepeaterRegionsSave,
  RepeaterRegionsSaved,
  RepeaterRegionsSaveFailed,
  RepeaterRegionsNoResponse,
  RepeaterRegionsRegions,
  RepeaterRegionsLoading,
  RepeaterRegionsWorking,
  RepeaterRegionsRegionName,
  Count
};

inline const char* generatedRepeaterRegionsLocaleString(uint8_t localeIndex,
                                                         RepeaterRegionsTextId id) {
  static const char* const STRINGS_0[] = {
    "Add region", "Delete region", "Save", "Saved", "Save failed",
    "[no response]", "Regions", "Loading...", "Working...", "Region name",
  };
  static const char* const STRINGS_1[] = {
    "Lägg till region", "Ta bort region", "Spara", "Sparat", "Kunde inte spara",
    "[inget svar]", "Regioner", "Laddar...", "Arbetar...", "Regionnamn",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterRegionsTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
