// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterRadioTextId : uint16_t {
  RepeaterRadioPreset,
  RepeaterRadioFrequency,
  RepeaterRadioBandwidth,
  RepeaterRadioSpreadFactor,
  RepeaterRadioSpreadingFactor,
  RepeaterRadioCodingRate,
  RepeaterRadioTxPower,
  RepeaterRadioSave,
  RepeaterRadioCustom,
  RepeaterRadioRadio,
  RepeaterRadioLoading,
  RepeaterRadioSaving,
  RepeaterRadioSaveFailed,
  RepeaterRadioSavedReboot,
  RepeaterRadioSelectSave,
  RepeaterRadioFrequencyMhz,
  RepeaterRadioTxPowerDbm,
  RepeaterRadioDiscardChanges,
  Count
};

inline const char* generatedRepeaterRadioLocaleString(uint8_t localeIndex,
                                                       RepeaterRadioTextId id) {
  static const char* const STRINGS_0[] = {
    "Preset", "Frequency", "Bandwidth", "Spread factor", "Spreading factor",
    "Coding rate", "TX power", "Save", "Custom", "Radio", "Loading...",
    "Saving...", "Save failed", "Saved - reboot to apply", "Select Save to apply",
    "Frequency (MHz)", "TX power (dBm)", "Discard changes?",
  };
  static const char* const STRINGS_1[] = {
    "Förinställning", "Frekvens", "Bandbredd", "Spridningsfaktor",
    "Spridningsfaktor", "Kodningsgrad", "Sändeffekt", "Spara", "Anpassad",
    "Radio", "Laddar...", "Sparar...", "Kunde inte spara",
    "Sparat - starta om för att tillämpa", "Välj Spara för att tillämpa",
    "Frekvens (MHz)", "Sändeffekt (dBm)", "Kassera ändringar?",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterRadioTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
