// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterNeighborsTextId : uint16_t {
  RepeaterNeighborsLoading,
  RepeaterNeighborsNoResponse,
  RepeaterNeighborsNeighbors,
  Count
};

inline const char* generatedRepeaterNeighborsLocaleString(uint8_t localeIndex,
                                                           RepeaterNeighborsTextId id) {
  static const char* const STRINGS_0[] = {
    "Loading...", "[no response]", "Neighbors",
  };
  static const char* const STRINGS_1[] = {
    "Laddar...", "[inget svar]", "Grannar",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterNeighborsTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
