// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class RepeaterActionsTextId : uint16_t {
  RepeaterActionsSendAdvert,
  RepeaterActionsSyncClock,
  RepeaterActionsReboot,
  RepeaterActionsRebooting,
  RepeaterActionsDone,
  RepeaterActionsNoResponse,
  RepeaterActionsActions,
  RepeaterActionsWorking,
  RepeaterActionsConfirmReboot,
  Count
};

inline const char* generatedRepeaterActionsLocaleString(uint8_t localeIndex,
                                                         RepeaterActionsTextId id) {
  static const char* const STRINGS_0[] = {
    "Send advert", "Sync clock", "Reboot", "Rebooting...", "Done",
    "[no response]", "Actions", "Working...", "Reboot repeater?",
  };
  static const char* const STRINGS_1[] = {
    "Skicka annons", "Synka klocka", "Starta om", "Startar om...", "Klart",
    "[inget svar]", "Åtgärder", "Arbetar...", "Starta om repeatern?",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)RepeaterActionsTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
