// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class ServerLoginTextId : uint16_t {
  ServerLoginRepeaterPassword,
  ServerLoginRoomPassword,
  ServerLoginRepeater,
  ServerLoginRoom,
  ServerLoginLoggingIn,
  ServerLoginBackToCancel,
  ServerLoginSavePassword,
  ServerLoginFailed,
  ServerLoginNoResponse,
  Count
};

inline const char* generatedServerLoginLocaleString(uint8_t localeIndex, ServerLoginTextId id) {
  static const char* const STRINGS_0[] = {
    "Repeater password",
    "Room password",
    "Repeater",
    "Room",
    "Logging in...",
    "Back to cancel",
    "Save password?",
    "Login failed",
    "No response",
  };
  static const char* const STRINGS_1[] = {
    "Repeaterlösenord",
    "Rumslösenord",
    "Repeater",
    "Rum",
    "Loggar in...",
    "Bakåt för att avbryta",
    "Spara lösenord?",
    "Inloggningen misslyckades",
    "Inget svar",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)ServerLoginTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
