// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class SetPathTextId : uint16_t {
  SetPathHashSize,
  SetPathPath,
  SetPathSave,
  SetPathPathHex,
  Count
};

inline const char* generatedSetPathLocaleString(uint8_t localeIndex, SetPathTextId id) {
  static const char* const STRINGS_0[] = {
    "Hash size",
    "Path",
    "Save",
    "Path (hex)",
  };
  static const char* const STRINGS_1[] = {
    "Hashstorlek",
    "Rutt",
    "Spara",
    "Rutt (hex)",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)SetPathTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
