// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class StatusTextId : uint16_t {
  StatusNoData,
  StatusUptime,
  StatusBattery,
  StatusAirTxRx,
  StatusRssiSnr,
  StatusNoise,
  StatusQueue,
  StatusSent,
  StatusReceived,
  StatusDuplicates,
  StatusReceiveErrors,
  StatusDebug,
  StatusClockUnset,
  StatusClock,
  StatusRefresh,
  StatusLoading,
  StatusNoResponse,
  Count
};

inline const char* generatedStatusLocaleString(uint8_t localeIndex, StatusTextId id) {
  static const char* const STRINGS_0[] = {
    "No data",
    "Uptime: %uh %02um",
    "Battery: %u.%02uV",
    "Air TX %s RX %s",
    "RSSI %d  SNR %.1f dB",
    "Noise %d dBm",
    "Queue: %u",
    "Sent %u f%u d%u",
    "Recv %u f%u d%u",
    "Dups f%u d%u",
    "RxErr: %u",
    "Debug: %u",
    "Clock: --",
    "Clock: %02u:%02u",
    "Refresh",
    "Loading...",
    "No response",
  };
  static const char* const STRINGS_1[] = {
    "Ingen data",
    "Drifttid: %uh %02um",
    "Batteri: %u.%02uV",
    "Sändtid TX %s RX %s",
    "RSSI %d  SNR %.1f dB",
    "Brus %d dBm",
    "Kö: %u",
    "Skickat %u f%u d%u",
    "Mottaget %u f%u d%u",
    "Dubbletter f%u d%u",
    "Mottagningsfel: %u",
    "Felsökning: %u",
    "Klocka: --",
    "Klocka: %02u:%02u",
    "Uppdatera",
    "Laddar...",
    "Inget svar",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)StatusTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
