// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class SystemInfoTextId : uint16_t {
  SystemInfoHeapFree,
  SystemInfoHeapMin,
  SystemInfoHeapTotal,
  SystemInfoContacts,
  SystemInfoStorage,
  SystemInfoStorageUnavailable,
  SystemInfoBattery,
  SystemInfoBatteryUnavailable,
  SystemInfoUptime,
  SystemInfoStatsUnavailable,
  SystemInfoFactoryResetKeepIdentity,
  SystemInfoFactoryResetFullWipe,
  SystemInfoConfirmKeepIdentity,
  SystemInfoConfirmFullWipe,
  Count
};

inline const char* generatedSystemInfoLocaleString(uint8_t localeIndex, SystemInfoTextId id) {
  static const char* const STRINGS_0[] = {
    "Heap free: %s",
    "Heap min: %s",
    "Heap total: %s",
    "Contacts: %u/%u",
    "Storage: %u/%uK",
    "Storage: --",
    "Battery: %u.%02uV",
    "Battery: --",
    "Uptime: %uh %02um",
    "Stats unavailable",
    "Factory Reset (keep identity)",
    "Factory Reset (full wipe)",
    "Erase data, keep identity. Can't undo.",
    "Erase all incl. identity. Can't undo.",
  };
  static const char* const STRINGS_1[] = {
    "Ledigt minne: %s",
    "Minst ledigt minne: %s",
    "Totalt minne: %s",
    "Kontakter: %u/%u",
    "Lagring: %u/%uK",
    "Lagring: --",
    "Batteri: %u.%02uV",
    "Batteri: --",
    "Drifttid: %uh %02um",
    "Statistik saknas",
    "Fabriksåterställ (behåll identitet)",
    "Fabriksåterställ (radera allt)",
    "Radera data, behåll identiteten. Kan inte ångras.",
    "Radera allt inkl. identiteten. Kan inte ångras.",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)SystemInfoTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
