// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {

enum class TelemetryDialogTextId : uint16_t {
  TelemetryDialogRequesting,
  TelemetryDialogNoResponse,
  TelemetryDialogNoFields,
  TelemetryDialogChannel,
  TelemetryDialogField,
  Count
};

inline const char* generatedTelemetryDialogLocaleString(uint8_t localeIndex, TelemetryDialogTextId id) {
  static const char* const STRINGS_0[] = {
    "Requesting...",
    "No response",
    "No fields",
    "%s ch%d:",
    "%s ch%d: %s",
  };
  static const char* const STRINGS_1[] = {
    "Begär...",
    "Inget svar",
    "Inga fält",
    "%s kanal %d:",
    "%s kanal %d: %s",
  };
  static const char* const* const TABLES[] = {
    STRINGS_0,
    STRINGS_1,
  };
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= 2 || textIndex >= (uint16_t)TelemetryDialogTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}

}  // namespace mishmesh
