#!/usr/bin/env python3
"""Generate compact C++ locale tables from mishmesh/locales/*.json.

The English file is the canonical key set. Other locales may omit keys; the
runtime falls back to English for those entries. Unknown keys and placeholder
mismatches are rejected so spelling mistakes do not silently ship.

System-info strings are emitted to a separate generated header to keep the
original TextId table stable while still using the same locale JSON files.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List

ROOT = Path(__file__).resolve().parents[1]
LOCALE_DIR = ROOT / "mishmesh" / "locales"
HEADER_PATH = ROOT / "mishmesh" / "core" / "LocaleStrings.h"
SYSTEM_INFO_HEADER_PATH = ROOT / "mishmesh" / "core" / "SystemInfoLocaleStrings.h"
TAG_RE = re.compile(r"^[a-z]{2}_[A-Z]{2}$")
PLACEHOLDER_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")


@dataclass(frozen=True)
class LocaleFile:
    tag: str
    native_name: str
    strings: Dict[str, str]


def enum_name(key: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", key)
    if not parts:
        raise ValueError(f"cannot create an enum name from key {key!r}")
    name = "".join(part[:1].upper() + part[1:] for part in parts)
    if name[0].isdigit():
        name = "Text" + name
    return name


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_locale(path: Path) -> LocaleFile:
    tag = path.stem
    if not TAG_RE.fullmatch(tag):
        raise ValueError(f"{path.name}: locale filename must look like en_US.json")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path.name}: {exc}") from exc
    if not isinstance(raw, dict):
        raise ValueError(f"{path.name}: root must be a JSON object")
    meta = raw.pop("_meta", None)
    if not isinstance(meta, dict):
        raise ValueError(f"{path.name}: _meta object is required")
    native_name = meta.get("nativeName") or meta.get("name")
    if not isinstance(native_name, str) or not native_name:
        raise ValueError(f"{path.name}: _meta.nativeName or _meta.name is required")
    for key, value in raw.items():
        if not isinstance(key, str) or not isinstance(value, str):
            raise ValueError(f"{path.name}: translation values must be strings ({key!r})")
    return LocaleFile(tag=tag, native_name=native_name, strings=raw)


def load_all() -> tuple[List[str], List[LocaleFile]]:
    paths = sorted(LOCALE_DIR.glob("*.json"))
    english_path = LOCALE_DIR / "en_US.json"
    if english_path not in paths:
        raise ValueError("mishmesh/locales/en_US.json is required")
    locales = [load_locale(english_path)]
    locales.extend(load_locale(path) for path in paths if path != english_path)

    keys = list(locales[0].strings.keys())
    if not keys:
        raise ValueError("en_US.json must contain at least one translation key")
    canonical = set(keys)

    enum_names: Dict[str, str] = {}
    for key in keys:
        name = enum_name(key)
        previous = enum_names.get(name)
        if previous is not None:
            raise ValueError(f"keys {previous!r} and {key!r} both map to TextId::{name}")
        enum_names[name] = key

    for locale in locales[1:]:
        unknown = sorted(set(locale.strings) - canonical)
        if unknown:
            raise ValueError(f"{locale.tag}: unknown keys: {', '.join(unknown)}")
        for key, translated in locale.strings.items():
            expected = sorted(PLACEHOLDER_RE.findall(locales[0].strings[key]))
            actual = sorted(PLACEHOLDER_RE.findall(translated))
            if expected != actual:
                raise ValueError(
                    f"{locale.tag}:{key}: placeholders {actual} do not match English {expected}"
                )
    return keys, locales


def generate_header(keys: Iterable[str], locales: List[LocaleFile]) -> str:
    key_list = list(keys)
    enum_rows = "\n".join(f"  {enum_name(key)}," for key in key_list)

    tables: List[str] = []
    for index, locale in enumerate(locales):
        rows = []
        for key in key_list:
            value = locale.strings.get(key)
            rows.append(f"    {cpp_string(value)}," if value is not None else "    nullptr,")
        tables.append(
            f"  static const char* const STRINGS_{index}[] = {{\n"
            + "\n".join(rows)
            + "\n  };"
        )

    descriptors = "\n".join(
        f"    {{{cpp_string(locale.tag)}, {cpp_string(locale.native_name)}}},"
        for locale in locales
    )
    table_refs = "\n".join(f"    STRINGS_{index}," for index in range(len(locales)))

    return f"""// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {{

enum class TextId : uint16_t {{
{enum_rows}
  Count
}};

struct LocaleDescriptor {{
  const char* tag;
  const char* name;
}};

inline uint8_t generatedLocaleCount() {{
  return {len(locales)};
}}

inline const LocaleDescriptor& generatedLocaleDescriptor(uint8_t index) {{
  static const LocaleDescriptor DESCRIPTORS[] = {{
{descriptors}
  }};
  if (index >= generatedLocaleCount()) index = 0;
  return DESCRIPTORS[index];
}}

inline const char* generatedLocaleString(uint8_t localeIndex, TextId id) {{
{chr(10).join(tables)}
  static const char* const* const TABLES[] = {{
{table_refs}
  }};
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= generatedLocaleCount() || textIndex >= (uint16_t)TextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}}

}}  // namespace mishmesh
"""


def generate_system_info_header(keys: Iterable[str], locales: List[LocaleFile]) -> str:
    key_list = list(keys)
    enum_rows = "\n".join(f"  {enum_name(key)}," for key in key_list)

    tables: List[str] = []
    for index, locale in enumerate(locales):
        rows = []
        for key in key_list:
            value = locale.strings.get(key)
            rows.append(f"    {cpp_string(value)}," if value is not None else "    nullptr,")
        tables.append(
            f"  static const char* const STRINGS_{index}[] = {{\n"
            + "\n".join(rows)
            + "\n  };"
        )
    table_refs = "\n".join(f"    STRINGS_{index}," for index in range(len(locales)))

    return f"""// Generated by tools/generate_locales.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace mishmesh {{

enum class SystemInfoTextId : uint16_t {{
{enum_rows}
  Count
}};

inline const char* generatedSystemInfoLocaleString(uint8_t localeIndex, SystemInfoTextId id) {{
{chr(10).join(tables)}
  static const char* const* const TABLES[] = {{
{table_refs}
  }};
  const uint16_t textIndex = (uint16_t)id;
  if (localeIndex >= {len(locales)} || textIndex >= (uint16_t)SystemInfoTextId::Count)
    return nullptr;
  return TABLES[localeIndex][textIndex];
}}

}}  // namespace mishmesh
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.write_text(content, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    try:
        keys, locales = load_all()
        system_info_keys = [key for key in keys if key.startswith("system_info.")]
        base_keys = [key for key in keys if not key.startswith("system_info.")]
        ok = write_or_check(HEADER_PATH, generate_header(base_keys, locales), args.check)
        if system_info_keys:
            ok = write_or_check(
                SYSTEM_INFO_HEADER_PATH,
                generate_system_info_header(system_info_keys, locales),
                args.check,
            ) and ok
        return 0 if ok else 1
    except ValueError as exc:
        print(f"locale generation failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
