#!/usr/bin/env python3
"""Generate compact C++ locale tables from mishmesh/locales/*.toml."""
from __future__ import annotations
import argparse,json,re,sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict,Iterable,List,Mapping,Tuple
try: import tomllib
except ModuleNotFoundError as e: raise SystemExit('Python 3.11+ is required') from e
ROOT=Path(__file__).resolve().parents[1]; LD=ROOT/'mishmesh'/'locales'; MAIN=ROOT/'mishmesh'/'core'/'LocaleStrings.h'
AREAS=[
('system_info.','SystemInfo'),('clock.','Clock'),('about.','About'),('airtime.','Airtime'),('onboarding.','Onboarding'),('set_path.','SetPath'),
('channel_share.','ChannelShare'),('chat_menu.','ChatMenu'),('chat_notify.','ChatNotify'),('clock_alert.','ClockAlert'),('command_line.','CommandLine'),
('contact_detail.','ContactDetail'),('discover_detail.','DiscoverDetail'),('join_private.','JoinPrivate'),('lock.','Lock'),('message_path.','MessagePath'),
('message_thread.','MessageThread'),('notification.','Notification'),('ping_dialog.','PingDialog'),('repeater_acl.','RepeaterAcl'),
('repeater_actions.','RepeaterActions'),('repeater_identity.','RepeaterIdentity'),('repeater_manage.','RepeaterManage'),('repeater_neighbors.','RepeaterNeighbors'),
('repeater_radio.','RepeaterRadio'),('repeater_regions.','RepeaterRegions'),('repeater_settings.','RepeaterSettings'),
('repeater_settings_panel.','RepeaterSettingsPanel'),('server_login.','ServerLogin'),('status.','Status'),('telemetry_dialog.','TelemetryDialog')]
AREA_HEADERS=[(p,s,ROOT/'mishmesh'/'core'/f'{s}LocaleStrings.h') for p,s in AREAS]
CLOCK=['clock.tab.stopwatch','clock.tab.timer','clock.tab.alarm','clock.tab.world','clock.tab.settings','clock.world.add_city','clock.stopwatch.running_hint','clock.stopwatch.resume_hint','clock.stopwatch.start_hint','clock.timer.paused','clock.timer.running_hint','clock.timer.resume_hint','clock.timer.set_hint','clock.alarm.clock_not_set','clock.alarm.rings_now','clock.alarm.rings_in_hours','clock.alarm.rings_in_minutes','clock.alarm.time_title','clock.alarm.time_label','clock.alarm.enabled_label','clock.alarm.set','clock.world.already_added','clock.world.city_removed']
TAG=re.compile(r'^[a-z]{2}_[A-Z]{2}$'); PH=re.compile(r'\{([A-Za-z_][A-Za-z0-9_]*)\}')
@dataclass(frozen=True)
class Locale: tag:str; name:str; strings:Dict[str,str]
def enum(k):
 p=re.findall(r'[A-Za-z0-9]+',k); n=''.join(x[:1].upper()+x[1:] for x in p)
 return ('Text'+n) if n and n[0].isdigit() else n
def flat(t:Mapping[str,object],pre=''):
 out={}
 for k,v in t.items():
  d=f'{pre}.{k}' if pre else k
  if isinstance(v,dict): out.update(flat(v,d))
  elif isinstance(v,str): out[d]=v
  else: raise ValueError(f'translation value must be string: {d}')
 return out
def load(p:Path):
 if not TAG.fullmatch(p.stem): raise ValueError(f'{p.name}: expected ll_CC.toml')
 try:
  with p.open('rb') as f: raw=tomllib.load(f)
 except (OSError,tomllib.TOMLDecodeError) as e: raise ValueError(f'{p.name}: {e}') from e
 meta=raw.get('meta'); name=meta.get('native_name') if isinstance(meta,dict) else None
 if not isinstance(name,str) or not name: raise ValueError(f'{p.name}: [meta].native_name is required')
 return Locale(p.stem,name,flat({k:v for k,v in raw.items() if k!='meta'}))
def load_all():
 paths=sorted(LD.glob('*.toml')); en=LD/'en_US.toml'
 if en not in paths: raise ValueError('mishmesh/locales/en_US.toml is required')
 ls=[load(en)]+[load(p) for p in paths if p!=en]; keys=list(ls[0].strings); canon=set(keys); names={}
 for k in keys:
  n=enum(k)
  if n in names: raise ValueError(f'keys {names[n]!r} and {k!r} map to {n}')
  names[n]=k
 for l in ls[1:]:
  unknown=sorted(set(l.strings)-canon)
  if unknown: raise ValueError(f'{l.tag}: unknown keys: {", ".join(unknown)}')
  for k,v in l.strings.items():
   if sorted(PH.findall(v))!=sorted(PH.findall(ls[0].strings[k])): raise ValueError(f'{l.tag}:{k}: placeholder mismatch')
 return keys,ls
def q(v): return json.dumps(v,ensure_ascii=False)
def tables(keys,ls):
 ts=[]
 for i,l in enumerate(ls):
  rows=[f'    {q(l.strings[k])},' if k in l.strings else '    nullptr,' for k in keys]
  ts.append(f'  static const char* const STRINGS_{i}[] = {{\n'+"\n".join(rows)+'\n  };')
 return '\n'.join(ts),'\n'.join(f'    STRINGS_{i},' for i in range(len(ls)))
def main_header(keys,ls):
 er='\n'.join(f'  {enum(k)},' for k in keys); ts,refs=tables(keys,ls)
 desc='\n'.join(f'    {{{q(l.tag)}, {q(l.name)}}},' for l in ls)
 return f'''// Generated by tools/generate_locales.py. Do not edit by hand.\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\nnamespace mishmesh {{\n\nenum class TextId : uint16_t {{\n{er}\n  Count\n}};\n\nstruct LocaleDescriptor {{\n  const char* tag;\n  const char* name;\n}};\n\ninline uint8_t generatedLocaleCount() {{\n  return {len(ls)};\n}}\n\ninline const LocaleDescriptor& generatedLocaleDescriptor(uint8_t index) {{\n  static const LocaleDescriptor DESCRIPTORS[] = {{\n{desc}\n  }};\n  if (index >= generatedLocaleCount()) index = 0;\n  return DESCRIPTORS[index];\n}}\n\ninline const char* generatedLocaleString(uint8_t localeIndex, TextId id) {{\n{ts}\n  static const char* const* const TABLES[] = {{\n{refs}\n  }};\n  const uint16_t textIndex = (uint16_t)id;\n  if (localeIndex >= generatedLocaleCount() || textIndex >= (uint16_t)TextId::Count)\n    return nullptr;\n  return TABLES[localeIndex][textIndex];\n}}\n\n}}  // namespace mishmesh\n'''
def area_header(keys,ls,stem):
 er='\n'.join(f'  {enum(k)},' for k in keys); ts,refs=tables(keys,ls)
 return f'''// Generated by tools/generate_locales.py. Do not edit by hand.\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\nnamespace mishmesh {{\n\nenum class {stem}TextId : uint16_t {{\n{er}\n  Count\n}};\n\ninline const char* generated{stem}LocaleString(uint8_t localeIndex, {stem}TextId id) {{\n{ts}\n  static const char* const* const TABLES[] = {{\n{refs}\n  }};\n  const uint16_t textIndex = (uint16_t)id;\n  if (localeIndex >= {len(ls)} || textIndex >= (uint16_t){stem}TextId::Count)\n    return nullptr;\n  return TABLES[localeIndex][textIndex];\n}}\n\n}}  // namespace mishmesh\n'''
def cpp_tokens(s):
 # Generated headers may have hand-formatted whitespace; compare while preserving string literals.
 return re.findall(r'"(?:\\.|[^"\\])*"|[A-Za-z_][A-Za-z0-9_:]*|\d+|[^\s]',s)
def write(path,content,check):
 old=path.read_text(encoding='utf-8') if path.exists() else None
 if old==content or (check and old is not None and cpp_tokens(old)==cpp_tokens(content)): return True
 if check: print(f'out of date: {path.relative_to(ROOT)}',file=sys.stderr); return False
 path.write_text(content,encoding='utf-8'); print(f'generated {path.relative_to(ROOT)}'); return True
def run():
 ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
 try:
  keys,ls=load_all(); split=tuple(p for p,_,_ in AREA_HEADERS); base=[k for k in keys if not k.startswith(split)]
  groups=[lambda k:k=='app.settings',lambda k:k.startswith('settings.'),lambda k:k.startswith('home.'),lambda k:k.startswith('app.') and k!='app.settings',lambda k:k.startswith('contacts.'),lambda k:k.startswith('messages.'),lambda k:k.startswith('advert.'),lambda k:k.startswith('radio.'),lambda k:k.startswith('time.'),lambda k:k.startswith('sound.')]
  ordered=[]; left=list(base)
  for pred in groups: ordered += [k for k in left if pred(k)]; left=[k for k in left if not pred(k)]
  ordered += left; ok=write(MAIN,main_header(ordered,ls),a.check)
  for p,s,path in AREA_HEADERS:
   ak=[k for k in keys if k.startswith(p)]
   if p=='clock.': ak=[k for k in CLOCK if k in set(ak)]+[k for k in ak if k not in CLOCK]
   if ak: ok=write(path,area_header(ak,ls,s),a.check) and ok
  return 0 if ok else 1
 except ValueError as e: print(f'locale generation failed: {e}',file=sys.stderr); return 2
if __name__=='__main__': raise SystemExit(run())
